---
title: "Create polygons from benjamini leaves"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create polygons from benjamini leaves}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(benjaminileaves)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(stringr)

set.seed(123)
```

```{r}
size <- 160
# df_branches <- tibble(
#   x = sample(1:size, 20, replace = TRUE), 
#   y = sample(1:size, 20, replace = TRUE), 
#   bezier_idx = rep(1:5, each = 4)
# )
xo = seq(-size/2, size/2, by = size/8) * 0.8
xm1 = xo * 0.75 - size/4
xm2 = xo * 0.75 + size/4
xu = xo * 0.5
y = rep(c(0.9, 0.5, 0.5, 0.1) * size, length(xo))
f <- function(xu, xm1, xm2, xo, y) {
  tibble(xu, xm1, xm2, xo) %>% 
    mutate(bezier_idx = row_number()) %>% 
    pivot_longer(-bezier_idx, values_to = "x") %>% 
    mutate(y = y) %>% 
    mutate()
}
df_branches <- f(xu, xm1, xm2, xo, y) %>% 
  mutate(x = x + size/2) %>% 
  mutate_at(
    c("x", "y"), 
    ~ .x + sample(
      (-size/20):(size/20), 
      length(xo), 
      replace = FALSE
    )
  )
```

```{r}
df_branches_and_leaves <- df_branches %>% 
  group_split(bezier_idx) %>% 
  map_dfr(
    ~benjamini_branch(df_branch = .x[c("x", "y")]),
    .id = "bezier_idx"
  )

df_branches_and_leaves %>%
  unite(idx, bezier_idx, i_branch, i_part, element, remove = FALSE) %>% 
  ggplot(aes(x = x, y = y, group = idx, color = factor(bezier_idx))) + 
  ggforce::geom_bezier2(show.legend = FALSE) +
  scale_y_reverse() +
  theme_void()
df2 <- df_branches_and_leaves %>%
  unite(idx, bezier_idx, i_branch, element, remove = FALSE) %>%
  gen_leaf_bezier_coords(idx, bezier_idx, i_branch, element, i_part) %>% 
  mutate(
    x2 = x + ambient::gen_simplex(x, y, frequency = 0.05, seed = 123),
    y2 = y + ambient::gen_simplex(x, y, frequency = 0.05, seed = 123)
  )

df2 %>% 
  filter(str_detect(element, "^half [12]$")) %>%
  ggplot(aes(x = x2, y = y2, group = idx, fill = factor(idx))) + 
  geom_path(
    data = df2 %>% 
      filter(!str_detect(element, "^half [12]$")), 
    aes(x = x2, y = y2, group = idx), 
    show.legend = FALSE, 
    color = "black"
  ) +
  geom_polygon(show.legend = FALSE, color = "black") +
  scale_y_reverse() +
  theme_void() 
```
