---
title: "Create a tree with benjamini leaves"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create a tree with benjamini leaves}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(benjaminileaves)
library(dplyr)
library(tidyr)
library(purrr)
# see here: https://github.com/djnavarro/flametree/
library(flametree)
library(ggplot2)
```

```{r}
ft <- flametree_grow(
    seg_wid = spark_decay(time = 0.3, multiplier = 3, constant = 0.1),
    seed = 21, 
    trees = 1, 
    time = 2, 
    angle = seq(-45, 45, 30), 
    split = 3
  ) 
ft_mod <- ft
ft_mod[1:2, "coord_y"] <- c(0.8, 0.9)
ft_mod <- ft_mod %>% 
  mutate_at(c("coord_x", "coord_y"), ~ . * 400)%>%
  group_by(coord_x, coord_y) %>%
  mutate(n = n()) %>%
  mutate(
    seg_wid = ifelse(n > 1, min(seg_wid), seg_wid),
    seg_col = ifelse(n > 1, max(seg_col), seg_col)
    ) %>%
  ungroup() %>%
  select(-n)

p <- flametree_plot(
  ft_mod, 
  background = "white",
  palette = c("brown", "forestgreen"))
p
```

```{r}
df_branches <- ft_mod %>% 
    filter(id_time == max(id_time)) %>% 
    group_by(id_path) %>% 
    summarise(tibble(x = coord_x[c(1, 2, 2, 3)], y = coord_y[c(1, 2, 2, 3)]))

df_leaves <- df_branches %>% 
  # rowwise() %>% 
  group_split() %>%
  map_dfr(benjamini_branch, .id = "branch") %>% 
  unite(i, i, branch)
```

```{r, fig.width=7, fig.height=7}
p <- flametree_plot(
  ft_mod %>% filter(id_time != max(id_time)), 
  background = "white"
)
 
p
p +
  geom_segment(
    data = df_leaves %>% drop_na(y1), 
    aes(x = x1, y = y1, xend = x2, yend = y2), 
    inherit.aes = FALSE,
    color = "brown"
  ) + 
  ggforce::geom_bezier(
    data = df_leaves %>% drop_na(x), 
    aes(x = x, y = y, group = i), 
    inherit.aes = FALSE,
    alpha = 0.5,
    color = "forestgreen"
  )
  
```
