#' Generate bezier coordinates of a leaf
#'
#' @param x1,y1 coordinates of the leaf origin
#' @param dx21,dy21,dx32,dy32,dx43,dy43 coordinates of the other control points (relative to the origin)
#' @param sx1,sx2,sx3,sx4 x coordinates of the control points
#' @param sy1,sy2,sy3,sy4 y coordinates of the control points
#' @param smx1,smx2,smy1,smy2 x & y coordinates of the middle vein control points
#'
#' @return named list with all parameters
#' @export
#'
#' @examples
#' gen_leaf_parameters()
gen_leaf_parameters <- function(
  # starting point (absolute coordinates)
  x1 = 10,
  y1 = 40,
  # distances to starting point (relative coordinates)
  dx21 = sample(12:20, 1),
  dy21 = sample(-4:-10, 1),
  dx32 = sample(10:18, 1),
  dy32 = stats::runif(1, 0.92 * (-dy21 - 1), 0.95 * (-dy21 - 1)),
  dx43 = sample(4:6, 1),
  dy43 = y1 + dy21 + dy32,
  # slopes
  sx1 = sample(1:3, 1),
  sx2 = sample(4:6, 1),
  sx3 = sample(2:4, 1),
  sx4 = stats::runif(1, 0, 0.2),
  sy1 = sample(-4:-6, 1),
  sy2 = stats::runif(1, -0.5, 0.5),
  sy3 = stats::runif(1, 0.5, 1.5),
  sy4 = stats::runif(1, 0.2, 0.7),
  # middle vein slopes:
  smx1 = sample(-5:-15, 1),
  smx2 = sample(-5:-15, 1),
  smy1 = stats::runif(1, -1, 1),
  smy2 = stats::runif(1, -1, 1)
) {
  tibble::lst(
    x1, y1, dx21,  dy21, dx32, dy32, dx43, dy43, sx1, sx2, sx3, sx4, sy1, sy2, sy3, sy4, smx1, smx2, smy1, smy2)
}

#' Generate bezier end points
#'
#' @param leaf_params parameters generated by `gen_leaf_parameters()`
#'
#' @return tibble with absolute coordinates
#' @export
#'
#' @examples
#' gen_benjamini_points()
gen_benjamini_points <- function(
  leaf_params = gen_leaf_parameters()
) {
  x1 = leaf_params$x1
  y1 = leaf_params$y1
  dx21 = leaf_params$dx21
  dy21 = leaf_params$dy21
  dx32 = leaf_params$dx32
  dy32 = leaf_params$dy32
  dx43 = leaf_params$dx43
  dy43 = leaf_params$dy43

  x2 <- x1 + dx21
  y2 <- y1 + dy21
  x3 <- x2 + dx32
  y3 <- y2 + dy32
  x4 <- x3 + dx43
  y4 <- y1

  tibble::tibble(
    x = c(x1, x2, x3, x4),
    y = c(y1, y2, y3, y4)
  )
}

#' Generate bezier slopes coordinates
#'
#' @param leaf_params parameters generated by `gen_leaf_parameters()`
#'
#' @return dataframe with sx1-4 in the x variable and sy1-4 in the y variable
#' @export
#'
#' @examples
#' gen_benjamini_slopes()
gen_benjamini_slopes <- function(
  leaf_params = gen_leaf_parameters()
) {
  sx1 = leaf_params$sx1
  sx2 = leaf_params$sx2
  sx3 = leaf_params$sx3
  sx4 = leaf_params$sx4
  sy1 = leaf_params$sy1
  sy2 = leaf_params$sy2
  sy3 = leaf_params$sy3
  sy4 = leaf_params$sy4

  tibble::tibble(
    x = c(sx1, sx2, sx3, sx4),
    y = c(sy1, sy2, sy3, sy4)
  )
}

#' Generate bezier slopes of the line in the middle of the leaf
#'
#' @param leaf_params parameters generated by `gen_leaf_parameters()`
#'
#' @return A dataframe containing the coordinates of the two control points of
#'   the bezier curve defining the midvein of the leaf.
#' @export
#'
#' @examples
#' gen_middle_line_slopes()
gen_middle_line_slopes <- function(
  leaf_params = gen_leaf_parameters()
)
  {
  smx1 = leaf_params$smx1
  smx2 = leaf_params$smx2
  smy1 = leaf_params$smy1
  smy2 = leaf_params$smy2
  tibble::tibble(
    x = c(smx1, smx2),
    y = c(smy1, smy2)
  )
}

#' Generate a dataframe of one bezier curve
#'
#' @param i number of the bezier
#' @param points_df dataframe generated by `gen_benjamini_points()` (see
#'   example).
#' @param slopes_df dataframe generated by `gen_benjamini_slopes()` (see
#'   example).
#'
#' @return A dataframe containing the information for one bezier curve in the format as needed by `ggforce::geom_bezier`.
#' @export
#'
#' @examples
#' set.seed(123)
#' leaf_params <- gen_leaf_parameters()
#' points_df <- gen_benjamini_points()
#' slopes_df <- gen_benjamini_slopes()
#' df_bezier <- get_one_bezier(1, points_df, slopes_df)
#' ggplot2::ggplot(df_bezier, ggplot2::aes(x = x, y = y)) + ggforce::geom_bezier()
get_one_bezier <- function(i, points_df, slopes_df) {
  dplyr::bind_rows(
    # points_df %>% dplyr::slice(i),
    points_df[i, ],
    # slopes_df %>% dplyr::slice(i) + points_df %>% dplyr::slice(i),
    slopes_df[i, ] + points_df[i, ],
    # -slopes_df %>% dplyr::slice(i + 1) + points_df %>% dplyr::slice(i + 1),
    -slopes_df[i + 1, ] + points_df[i + 1, ],
    # points_df %>% dplyr::slice(i + 1)
    points_df[i + 1, ]
  )
}

gen_middle_line_points <- function(points_df) {
  dplyr::bind_rows(
    points_df %>% dplyr::slice_tail(),
    points_df %>% dplyr::slice_head()
  )
}


#' Generate bezier curve coordinates of a benjamini leaf
#' @inheritParams get_one_bezier
#' @param slopes_middle_df slopes of the bezier curve separating the leaf in the middle
#' @param omega rotation angle of the leaf
#' @param xrot rotation x coordinate
#' @param yrot rotation y coordinate
#' @param precision numeric precision of the output
#'
#'
#' @return A dataframe conaining the data for the bezier curves of a leaf (see example).
#' @export
#' @importFrom rlang .data
#' @examples
#' df <- benjamini_leaf()
#' df
#' ggplot2::ggplot(df) +
#'   ggforce::geom_bezier(ggplot2::aes(x = x, y = y, group = i))
benjamini_leaf <- function(
  leaf_params = gen_leaf_parameters(),
  omega = 0, xrot = points_df$x[1], yrot = points_df$y[1], precision = 2
  ) {
  points_df = gen_benjamini_points(leaf_params)
  slopes_df = gen_benjamini_slopes(leaf_params)
  slopes_middle_df = gen_middle_line_slopes(leaf_params)
  points_middle_df = gen_middle_line_points(points_df)
  middle_line_df <- get_one_bezier(1, points_middle_df, slopes_middle_df)
  upper_half <- 1:3 %>%
    purrr::map_dfr(
      ~get_one_bezier(.x, points_df, slopes_df),
      .id = "i"
    )  %>%
    dplyr::bind_rows(middle_line_df %>% dplyr::mutate(i = "4"))
  lower_half <-  1:3 %>%
    purrr::map_dfr(
      ~get_one_bezier(
        .x,
        points_df %>% rev_points(),
        slopes_df %>% dplyr::mutate(y = -y)
      ),
      .id = "i"
    ) %>%
    dplyr::mutate(i = paste0(.data$i, "r"))  %>%
    dplyr::bind_rows(middle_line_df %>% dplyr::mutate(i = "4r"))

  df <- dplyr::bind_rows(upper_half, lower_half)
  if (omega != 0) {
    return(
      rotate_bezier_df(df, alpha = omega, xrot = xrot, yrot = yrot, precision = precision)
    )
  }
  df
}


rev_points <- function(points_df) {
  points_df_rev <- points_df
  points_df_rev$y[-1] <- - points_df_rev$y[-1] + points_df_rev$y[1] + points_df_rev$y[1]
  points_df_rev
}

# from here: https://stackoverflow.com/a/15464420
rotate_bezier_df <- function(bezier_df, alpha = 30, xrot = bezier_df$x[1], yrot = bezier_df$y[1], precision = 2) {

  alpha_rad <- alpha / 90 * pi / 2
  rotm <- matrix(c(cos(alpha_rad),sin(alpha_rad),-sin(alpha_rad),cos(alpha_rad)),ncol=2)
  #shift, rotate, shift back

  M <- bezier_df %>% dplyr::select(-.data$i) %>% as.matrix()
  t(rotm %*% (t(M) - c(xrot, yrot)) + c(xrot, yrot)) %>%
    round(precision) %>%
    tibble::as_tibble(.name_repair = "minimal") %>%
    purrr::set_names(c("x", "y")) %>%
    dplyr::mutate(i = bezier_df$i)
}
